language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t sagarbhp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sagarbhp/react-test npm run test

after_success:
  - docker build -t sagarbhp/multi-client ./client
  - docker build -t sagarbhp/multi-nginx ./nginx
  - docker build -t sagarbhp/multi-server ./server
  - docker build -t sagarbhp/multi-worker ./worker
  # Push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sagarbhp/multi-client
  - docker push sagarbhp/multi-nginx
  - docker push sagarbhp/multi-server
  - docker push sagarbhp/multi-worker

deploy:
  provider: elasticbeanstack
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-441046298192"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY